services:
  zapp:
    env_file:
      - .env
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - zokrates
      - timber
      - zapp-mongo
    healthcheck:
      test: curl -f http://localhost:3000/healthcheck || exit 1
      interval: 2s
      timeout: 1s
      retries: 120
      start_period: 1s
      start_interval: 2s
    volumes:
      - ./build:/app/build
      - ./contracts/:/app/contracts/
      - ./circuits/:/app/circuits
      - ./orchestration/:/app/orchestration
      - ./config/:/app/config
    environment:
      RPC_URL: ${SWAPESCROW_RPC_URL}
      DEFAULT_ACCOUNT: ${DEFAULT_ACCOUNT}
      KEY: ${KEY}
      LOG_LEVEL: info
      MONGO_URL: mongodb://admin:admin@zapp-mongo:27017
      MONGO_NAME: zapp_db
      TIMBER_URL: http://timber
    restart: on-failure
    networks:
      - zapp_network

  zokrates:
    image: ghcr.io/eyblockchain/zokrates-worker-updated:latest
    # platform: linux/arm64/v8
    volumes:
      - ./circuits/:/app/circuits
      - ./proving-files/:/app/output
      - ./orchestration/common/write-vk.mjs:/app/write-vk.mjs
      - ./orchestration/common/db/:/app/orchestration/common/db
    environment:
      PROVING_SCHEME: 'g16'
    ports:
      - '8080:80'
    networks:
      - zapp_network

  timber:
    env_file:
      - .env
    build: 
      context: https://github.com/eybrativosdigitais/timber.git#starlight-timber:merkle-tree
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - timber-mongo
    volumes:
      - ./config/:/app/config
      - ./contracts/:/app/contracts
      - ./build/:/app/build
    ports:
      - '3100:80'
    environment:
      HASH_TYPE: 'mimc'
      LOG_LEVEL: 'debug'
      UNIQUE_LEAVES: 'true'
      DEFAULT_GAS: ${DEFAULT_GAS}
      DEFAULT_GAS_PRICE: ${DEFAULT_GAS_PRICE}
      RPC_URL: ${SWAPESCROW_RPC_URL}
      DEFAULT_ACCOUNT: ${DEFAULT_ACCOUNT}
      KEY: ${KEY}
      CONTRACT_LOCATION: 'default'      
      DB_URL: mongodb://admin:admin@timber-mongo:27017
    networks:
      - zapp_network

  #The database storing the merkle tree
  timber-mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=merkle_tree
    volumes:
      - timber-mongo-volume:/data/db
      - ./config:/app/config/
    networks:
      - zapp_network

    #The database storing commitments
  zapp-mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=zapp_db
    volumes:
      - zapp-commitment-volume:/data/db
    networks:
      - zapp_network

volumes:
  timber-mongo-volume: {}
  zapp-commitment-volume: {}

networks:
  zapp_network:
    name: zapp_network